name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Buildar projeto
        run: CI=false npm run build

      - name: Deploy (
        run: echo "Deploy feito com sucesso"
