name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Buildar projeto
        if: success()
        run: CI=false npm run build

      - name: Deploy (placeholder)
        if: success()
        run: echo "Deploy feito com sucesso"
